[package]
name = "hammersbald"
version = "0.2.3"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/hammersbald/"
repository = "https://github.com/rust-bitcoin/hammersbald/"
documentation = "https://github.com/rust-bitcoin/hammersbald/"
description = "Hammersbald - fast persistent store for a blockchain"
keywords = [ "blockchain", "bitcoin", "hammersbald" ]
readme = "README.md"

[lib]
name = "hammersbald"
path = "src/lib.rs"

[features]
bitcoin_support=["bitcoin"]

[dependencies]
rand="0.5"
siphasher = "0.2"
byteorder="1"
bitcoin={version="0.14", optional=true}

[dev-dependencies]
hex = "0.3"
